/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banquier;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import java.rmi.Naming;
import rmi.IAgent;

/**
 *
 * @author User
 */
public class FormeGenerale extends javax.swing.JFrame {

    /**
     * Creates new form FormeGenerale
     */
 
    public FormeGenerale() {
        initComponents();
        //centrer la fenetre
        this.setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e){
                new Login().setVisible(true);
            }
        });
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bt_creerCompte = new javax.swing.JButton();
        Bt_ModifierCompte = new javax.swing.JButton();
        Bt_Operation = new javax.swing.JButton();
        Bt_ListeComptes1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACCUEIL");
        setResizable(false);

        Bt_creerCompte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_creerCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.jpg"))); // NOI18N
        Bt_creerCompte.setText("CREER UN COMPTE");
        Bt_creerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_creerCompteActionPerformed(evt);
            }
        });

        Bt_ModifierCompte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_ModifierCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        Bt_ModifierCompte.setText("MODIFIER COMPTE");
        Bt_ModifierCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ModifierCompteActionPerformed(evt);
            }
        });

        Bt_Operation.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_Operation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4.jpg"))); // NOI18N
        Bt_Operation.setText("OPERATIONS");
        Bt_Operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_OperationActionPerformed(evt);
            }
        });

        Bt_ListeComptes1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Bt_ListeComptes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        Bt_ListeComptes1.setText("LISTE DES COMPTES");
        Bt_ListeComptes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ListeComptes1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bt_ListeComptes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bt_creerCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bt_Operation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bt_ModifierCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bt_creerCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(Bt_Operation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bt_ModifierCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(Bt_ListeComptes1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_creerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_creerCompteActionPerformed

        try {
             IAgent  J = (IAgent) Naming.lookup("rmi://localhost:1099/BANQUE");
              //Génère un numéro de compte unique
            String numCpte = J.GenererMDP();
            
            new CreationCompte(numCpte);
            this.dispose();
                
        }catch (RemoteException ex4) {
        JOptionPane.showMessageDialog(null,"La connexion au serveur a échoué","Serveur non démarré",JOptionPane.WARNING_MESSAGE);
       }
       catch (MalformedURLException ex4) {
            JOptionPane.showMessageDialog(null,"Connexion 2","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
       }
       catch (NotBoundException ex4) {
             JOptionPane.showMessageDialog(null,"Serveur non joignable","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_Bt_creerCompteActionPerformed

    private void Bt_ListeComptes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ListeComptes1ActionPerformed
        new LISTECOMPTE();
        this.dispose();
    }//GEN-LAST:event_Bt_ListeComptes1ActionPerformed

    private void Bt_OperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_OperationActionPerformed
        new GestionnaireCompte();
        this.dispose();
    }//GEN-LAST:event_Bt_OperationActionPerformed

    private void Bt_ModifierCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ModifierCompteActionPerformed
        new MODIFIERCOMPTE();
        this.dispose();
    }//GEN-LAST:event_Bt_ModifierCompteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormeGenerale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormeGenerale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormeGenerale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormeGenerale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormeGenerale().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_ListeComptes1;
    private javax.swing.JButton Bt_ModifierCompte;
    private javax.swing.JButton Bt_Operation;
    private javax.swing.JButton Bt_creerCompte;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
