/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banquier;

import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static javax.xml.ws.Service.Mode.MESSAGE;
import rmi.IAgent;
import rmi.IClient;
import rmi.IOperation;

/**
 *
 * @author HP
 */
public class GestionnaireCompte extends javax.swing.JFrame {

    /**
     * Creates new form GestionnaireCompte
     */

    DefaultTableModel model;
    public GestionnaireCompte() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e){
                new FormeGenerale().setVisible(true);
            }
        });
        model = new DefaultTableModel();
        this.setVisible(true);
        //EvtAutres();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtNomClient = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtPrennom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Txtbox_dateCreation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtNumeroCompte = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Txtbox_solde = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtBoxTypeCompte = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Txtbox_telephone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_infoClient = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        TxtBox_recherche = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Bt_valider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Bt_versement = new javax.swing.JButton();
        Bt_Retrait = new javax.swing.JButton();
        Bt_Actualiser = new javax.swing.JButton();
        Bt_Virement = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GESTIONNAIRE COMPTE");
        setLocation(new java.awt.Point(500, 500));
        setResizable(false);

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("  NOM CLIENT :");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TxtNomClient.setEditable(false);
        TxtNomClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("PRENOMS CLIENT :");

        TxtPrennom.setEditable(false);
        TxtPrennom.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TxtPrennom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPrennomActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("DATE CREATION :");

        Txtbox_dateCreation.setEditable(false);
        Txtbox_dateCreation.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Txtbox_dateCreation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtbox_dateCreationActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText("  NUMERO  COMPTE:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TxtNumeroCompte.setEditable(false);
        TxtNumeroCompte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("SOLDE :");

        Txtbox_solde.setEditable(false);
        Txtbox_solde.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Txtbox_solde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtbox_soldeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("    TYPE DE COMPTE :");

        TxtBoxTypeCompte.setEditable(false);
        TxtBoxTypeCompte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TxtBoxTypeCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBoxTypeCompteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("TELEPHONE :");

        Txtbox_telephone.setEditable(false);
        Txtbox_telephone.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtNumeroCompte))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtBoxTypeCompte, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(Txtbox_telephone)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txtbox_solde, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(TxtPrennom)
                            .addComponent(TxtNomClient)
                            .addComponent(Txtbox_dateCreation))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNumeroCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPrennom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBoxTypeCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_dateCreation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_solde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Table_infoClient.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Table_infoClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_infoClient.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Table_infoClient);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TxtBox_recherche.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TxtBox_recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtBox_rechercheMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("  NUMERO  COMPTE:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Bt_valider.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Bt_valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recherche.jpg"))); // NOI18N
        Bt_valider.setText("Valider");
        Bt_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtBox_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bt_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_valider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Historique des opérations");

        Bt_versement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_versement.setText("Versement");
        Bt_versement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_versementActionPerformed(evt);
            }
        });

        Bt_Retrait.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Retrait.setText("Retrait");
        Bt_Retrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_RetraitActionPerformed(evt);
            }
        });

        Bt_Actualiser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rafraichir2.png"))); // NOI18N
        Bt_Actualiser.setText("Actualiser");
        Bt_Actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_ActualiserActionPerformed(evt);
            }
        });

        Bt_Virement.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Virement.setText("Virement");
        Bt_Virement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_VirementActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        jMenu2.setText("A propos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/help.png"))); // NOI18N
        jMenuItem1.setText("À propos du logiciel");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Bt_versement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Retrait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Virement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bt_Actualiser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(Bt_versement)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bt_Retrait)
                                .addGap(18, 18, 18)
                                .addComponent(Bt_Virement)
                                .addGap(18, 18, 18)
                                .addComponent(Bt_Actualiser))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtPrennomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPrennomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPrennomActionPerformed

    private void Txtbox_dateCreationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtbox_dateCreationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtbox_dateCreationActionPerformed

    private void Bt_ActualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_ActualiserActionPerformed
//        TxtBox_recherche.setText("");
//        TxtNumeroCompte.setText("");
//        TxtNomClient.setText("");
//        TxtPrennom.setText("");
//        TxtBoxTypeCompte.setText("");
//        Txtbox_telephone.setText("");
//        Txtbox_dateCreation.setText("");
//        Txtbox_solde.setText("");
        ViderTable(model);
        try {
             IOperation  J = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
             //String[] InfoClient = J.Consultation(TxtBox_recherche.getText());
             DefaultTableModel modelInfo = J.Consultation(TxtBox_recherche.getText());
             if(modelInfo.getRowCount() == 0){
                //JOptionPane.showMessageDialog(null,"Ce compte n'existe pas !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
             }
             else{
                
                    TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
                    TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
                    TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
                    TxtBoxTypeCompte.setText(modelInfo.getValueAt(0, 3).toString());
                    Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
                    Txtbox_dateCreation.setText(modelInfo.getValueAt(0, 5).toString());
                    Txtbox_solde.setText(modelInfo.getValueAt(0, 6).toString());

                    //On remplit la liste des infos sur les transactions effectuées
                    model = J.ListeOperation(TxtNumeroCompte.getText());
                    Table_infoClient.setModel(model);
                 
             }
                
        }catch (RemoteException ex4) {
        JOptionPane.showMessageDialog(null,"La connexion au serveur a échoué","Serveur non démarré",JOptionPane.WARNING_MESSAGE);
       }
       catch (MalformedURLException ex4) {
            JOptionPane.showMessageDialog(null,"Connexion 2","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
       }
       catch (NotBoundException ex4) {
             JOptionPane.showMessageDialog(null,"Serveur non joignable","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Bt_ActualiserActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this,"GesCompte est un logiciel de  prennant en compte:\n"
                        + "-Consultation de liste de compte enregistrés, "
                + "\n-Effectuer un versement, "
                + "\n-Effectuer un retrait,"
                + "\n-Effectuer un virement,"
                + "\n-Modifier un compte"
                + "\n\nCe logiciel a été édité par : \nDIAKITE SOUMAILA\nKERE BACHIR\nKONE SIDNEY AZIZ \nKOFFI DESIRE\nN'GUESSAN HENRI AIME", "A propos",JOptionPane.INFORMATION_MESSAGE);
	
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TxtBox_rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBox_rechercheMouseClicked
        ViderTable(model);
        TxtBox_recherche.setText("");
    }//GEN-LAST:event_TxtBox_rechercheMouseClicked

    private void Txtbox_soldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtbox_soldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtbox_soldeActionPerformed

    private void Bt_versementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_versementActionPerformed
        if(TxtNumeroCompte.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Choisissez un compte svp !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            new VERSEMENT(TxtNumeroCompte.getText().toString());
        }
    }//GEN-LAST:event_Bt_versementActionPerformed

    private void Bt_RetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_RetraitActionPerformed
        if(TxtNumeroCompte.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Choisissez un compte svp !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            new RETRAIT(TxtNumeroCompte.getText());
        }
    }//GEN-LAST:event_Bt_RetraitActionPerformed

    private void Bt_VirementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_VirementActionPerformed
       if(TxtNumeroCompte.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Choisissez un compte svp !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE);
        }else{
            new VIREMENT(TxtNumeroCompte.getText());
        } 
    }//GEN-LAST:event_Bt_VirementActionPerformed

    private void TxtBoxTypeCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBoxTypeCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBoxTypeCompteActionPerformed

    private void Bt_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_validerActionPerformed
        if(TxtBox_recherche.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Entrez un numéro de compte !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
        }else{
            try {
             IOperation  J = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
             //String[] InfoClient = J.Consultation(TxtBox_recherche.getText());
             DefaultTableModel modelInfo = J.Consultation(TxtBox_recherche.getText());
             if(modelInfo.getRowCount() == 0){
                JOptionPane.showMessageDialog(null,"Ce compte n'existe pas !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
             }
             else{
                
                    TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
                    TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
                    TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
                    TxtBoxTypeCompte.setText(modelInfo.getValueAt(0, 3).toString());
                    Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
                    Txtbox_dateCreation.setText(modelInfo.getValueAt(0, 5).toString());
                    Txtbox_solde.setText(modelInfo.getValueAt(0, 6).toString());

                    //On remplit la liste des infos sur les transactions effectuées
                    model = J.ListeOperation(TxtNumeroCompte.getText());
                    Table_infoClient.setModel(model);
                 
             }
                
        }catch (RemoteException ex4) {
        JOptionPane.showMessageDialog(null,"La connexion au serveur a échoué","Serveur non démarré",JOptionPane.WARNING_MESSAGE);
       }
       catch (MalformedURLException ex4) {
            JOptionPane.showMessageDialog(null,"Connexion 2","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
       }
       catch (NotBoundException ex4) {
             JOptionPane.showMessageDialog(null,"Serveur non joignable","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_Bt_validerActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GestionnaireCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GestionnaireCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GestionnaireCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GestionnaireCompte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GestionnaireCompte().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Actualiser;
    private javax.swing.JButton Bt_Retrait;
    private javax.swing.JButton Bt_Virement;
    private javax.swing.JButton Bt_valider;
    private javax.swing.JButton Bt_versement;
    private javax.swing.JTable Table_infoClient;
    private javax.swing.JTextField TxtBoxTypeCompte;
    private javax.swing.JTextField TxtBox_recherche;
    private javax.swing.JTextField TxtNomClient;
    private javax.swing.JTextField TxtNumeroCompte;
    private javax.swing.JTextField TxtPrennom;
    private javax.swing.JTextField Txtbox_dateCreation;
    private javax.swing.JTextField Txtbox_solde;
    private javax.swing.JTextField Txtbox_telephone;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    public void ViderTable(DefaultTableModel model){
        int i=model.getRowCount()-1;
        while(i!= -1){
            model.removeRow(i);
            i--;
        }
 

    }
//public void EvtAutres(){
//        TxtBox_recherche.getDocument().addDocumentListener(new DocumentListener(){
//            public void changedUpdate(DocumentEvent e){
//                try {
//                IOperation stub = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
//                model = stub.Consultation(TxtBox_recherche.getText());
//                 if(model.getRowCount() == 0){
//                //JOptionPane.showMessageDialog(null,"Ce compte n'existe pas !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
//                }
//                else{
//                    Table_infoClient.setModel(model);
//                 }
// 
//                DefaultTableModel modelInfo = stub.Consultation(TxtBox_recherche.getText());
//                if(modelInfo.getRowCount() != 0){
//                      
//                    TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
//                    TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
//                    TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
//                    TxtBoxTypeCompte.setText(modelInfo.getValueAt(0, 3).toString());
//                    Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
//                    Txtbox_dateCreation.setText(modelInfo.getValueAt(0, 5).toString());
//                    Txtbox_solde.setText(modelInfo.getValueAt(0, 6).toString());
//                }
//
//                } catch (NotBoundException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                } catch (MalformedURLException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                } catch (RemoteException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                }
//                
//                
//        
//            }
//            public void insertUpdate(DocumentEvent e){
//                try {
//                IOperation stub = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
//                model = stub.Consultation(TxtBox_recherche.getText());
//                 if(model.getRowCount() == 0){
//                //JOptionPane.showMessageDialog(null,"Ce compte n'existe pas !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
//                }
//                else{
//                    Table_infoClient.setModel(model);
//                 }
// 
//                DefaultTableModel modelInfo = stub.Consultation(TxtBox_recherche.getText());
//                if(modelInfo.getRowCount() != 0){
//                      
//                    TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
//                    TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
//                    TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
//                    TxtBoxTypeCompte.setText(modelInfo.getValueAt(0, 3).toString());
//                    Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
//                    Txtbox_dateCreation.setText(modelInfo.getValueAt(0, 5).toString());
//                    Txtbox_solde.setText(modelInfo.getValueAt(0, 6).toString());
//                }
//                } catch (NotBoundException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                } catch (MalformedURLException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                } catch (RemoteException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                }
//            }
//            public void removeUpdate(DocumentEvent e){
//            try {
//                IOperation stub = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
//                model = stub.Consultation(TxtBox_recherche.getText());
//                 if(model.getRowCount() == 0){
//                //JOptionPane.showMessageDialog(null,"Ce compte n'existe pas !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
//                }
//                else{
//                    Table_infoClient.setModel(model);
//                 }
// 
//                DefaultTableModel modelInfo = stub.Consultation(TxtBox_recherche.getText());
//                if(modelInfo.getRowCount() != 0){
//                      
//                    TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
//                    TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
//                    TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
//                    TxtBoxTypeCompte.setText(modelInfo.getValueAt(0, 3).toString());
//                    Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
//                    Txtbox_dateCreation.setText(modelInfo.getValueAt(0, 5).toString());
//                    Txtbox_solde.setText(modelInfo.getValueAt(0, 6).toString());
//                }
//                } catch (NotBoundException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                } catch (MalformedURLException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                } catch (RemoteException ex) {
//                     JOptionPane.showMessageDialog(null,"Erreur RMI,problème de connexion avec le serveur","ERREUR",JOptionPane.ERROR_MESSAGE);
//                }
//
//            }
//        });
//        
//    }

}
