/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banquier;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rmi.IAgent;
import rmi.IOperation;

/**
 *
 * @author HP
 */
public class MODIFIERCOMPTE extends javax.swing.JFrame {

    /**
     * Creates new form MODIFIERCOMPTE
     */
    public MODIFIERCOMPTE() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e){
                new FormeGenerale().setVisible(true);
            }
        });
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtBox_recherche = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Bt_valider = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TxtNomClient = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtPrennom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Txtbox_telephone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TxtNumeroCompte = new javax.swing.JTextField();
        Bt_Enregistrer = new javax.swing.JButton();
        Combox_typeCompte = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Txtbox_adresse = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TxtBox_mdp = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MODIFIER COMPTE");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TxtBox_recherche.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        TxtBox_recherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtBox_rechercheMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("  NUMERO  COMPTE:");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        Bt_valider.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Bt_valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recherche.jpg"))); // NOI18N
        Bt_valider.setText("Valider");
        Bt_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtBox_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bt_valider, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBox_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_valider))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("  NOM CLIENT :");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TxtNomClient.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("PRENOMS CLIENT :");

        TxtPrennom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("  TYPE DE COMPTE :");

        Txtbox_telephone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("TELEPHONE :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setText(" NUMERO  COMPTE:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        TxtNumeroCompte.setEditable(false);
        TxtNumeroCompte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Bt_Enregistrer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Bt_Enregistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save.png"))); // NOI18N
        Bt_Enregistrer.setText("Enregistrer");
        Bt_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_EnregistrerActionPerformed(evt);
            }
        });

        Combox_typeCompte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Combox_typeCompte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPTE EPARGNE", "COMPTE BANCAIRE COURANT", "COMPTE TITRE", "COMPTE INDIVIDUEL", "COMPTE JOINT" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setText("ADRESSE :");

        Txtbox_adresse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setText("MOT DE PASSE :");

        TxtBox_mdp.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bt_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17))
                                    .addGap(8, 8, 8)))
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtNumeroCompte, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtPrennom)
                            .addComponent(TxtNomClient)
                            .addComponent(Txtbox_telephone)
                            .addComponent(Combox_typeCompte, 0, 287, Short.MAX_VALUE)
                            .addComponent(Txtbox_adresse, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtBox_mdp))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNumeroCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtPrennom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Combox_typeCompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtbox_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TxtBox_mdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Bt_Enregistrer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBox_rechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtBox_rechercheMouseClicked

    }//GEN-LAST:event_TxtBox_rechercheMouseClicked

    private void Bt_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_validerActionPerformed
        if(TxtBox_recherche.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Entrez un numéro de compte svp !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
        }else{
            try {
             IOperation  J = (IOperation) Naming.lookup("rmi://localhost:1099/BANQUE");
             //String[] InfoClient = J.Consultation(TxtBox_recherche.getText());
             DefaultTableModel modelInfo = J.Consultation(TxtBox_recherche.getText());
             if(modelInfo.getRowCount() == 0){
                JOptionPane.showMessageDialog(null,"Ce compte n'existe pas !!!","INFO COMPTE",JOptionPane.INFORMATION_MESSAGE); 
             }
             else{
                    TxtNumeroCompte.setText(modelInfo.getValueAt(0, 0).toString());
                    TxtNomClient.setText(modelInfo.getValueAt(0, 1).toString());
                    TxtPrennom.setText(modelInfo.getValueAt(0, 2).toString());
                    Combox_typeCompte.setSelectedItem(modelInfo.getValueAt(0, 3).toString());
                    Txtbox_telephone.setText(modelInfo.getValueAt(0, 4).toString());
                    Txtbox_adresse.setText(modelInfo.getValueAt(0, 7).toString());
                    TxtBox_mdp.setText(modelInfo.getValueAt(0, 8).toString());
                    
             }
                
        }catch (RemoteException ex4) {
        JOptionPane.showMessageDialog(null,"La connexion au serveur a échoué","Serveur non démarré",JOptionPane.WARNING_MESSAGE);
       }
       catch (MalformedURLException ex4) {
            JOptionPane.showMessageDialog(null,"La connexion au serveur a échoué","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
       }
       catch (NotBoundException ex4) {
             JOptionPane.showMessageDialog(null,"Serveur non joignable","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_Bt_validerActionPerformed

    private void Bt_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_EnregistrerActionPerformed
        if(TxtNomClient.getText().equals("") || TxtPrennom.getText().equals("")|| Txtbox_telephone.getText().equals("")||
                Txtbox_adresse.getText().equals("")|| TxtBox_mdp.getPassword().length == 0){
            JOptionPane.showMessageDialog(null,"Remplissez tous les champs SVP !!!!","CHAMPS VIDES",JOptionPane.ERROR_MESSAGE);
        }else{
                try {
             IAgent  J = (IAgent) Naming.lookup("rmi://localhost:1099/BANQUE");
              //Génère un numéro de compte unique
              J.ModifierUnCompte(TxtNumeroCompte.getText(), TxtNomClient.getText(), TxtPrennom.getText(), Txtbox_adresse.getText(), 
                      Txtbox_telephone.getText(), Combox_typeCompte.getSelectedItem().toString(), TxtBox_mdp.getPassword().toString());
              //this.dispose();
              JOptionPane.showMessageDialog(null,"Modification effectuée avec succès","MODIFICATION",JOptionPane.INFORMATION_MESSAGE);
              
                
                }catch (RemoteException ex4) {
                JOptionPane.showMessageDialog(null,"La connexion au serveur a échoué","Serveur non démarré",JOptionPane.WARNING_MESSAGE);
               }
               catch (MalformedURLException ex4) {
                    JOptionPane.showMessageDialog(null,"Connexion 2","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
               }
               catch (NotBoundException ex4) {
                     JOptionPane.showMessageDialog(null,"Serveur non joignable","Erreur de connexion",JOptionPane.WARNING_MESSAGE);
                }
        }
        
    }//GEN-LAST:event_Bt_EnregistrerActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MODIFIERCOMPTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MODIFIERCOMPTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MODIFIERCOMPTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MODIFIERCOMPTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MODIFIERCOMPTE().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Enregistrer;
    private javax.swing.JButton Bt_valider;
    private javax.swing.JComboBox<String> Combox_typeCompte;
    private javax.swing.JPasswordField TxtBox_mdp;
    private javax.swing.JTextField TxtBox_recherche;
    private javax.swing.JTextField TxtNomClient;
    private javax.swing.JTextField TxtNumeroCompte;
    private javax.swing.JTextField TxtPrennom;
    private javax.swing.JTextField Txtbox_adresse;
    private javax.swing.JTextField Txtbox_telephone;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
